version: 2.1

commands:
  build:
    parameters:
      docker_tag:
        default: "native"
        type: string
    steps:
      - checkout
      #- setup_remote_docker
      #- restore_cache:
      #    keys:
      #      - v1-{{ .Branch }}
      #    paths:
      #      - /caches/app.tar
      #- run:
      #    name: Load Docker image layer cache
      #    command: |
      #      docker load -i /caches/app.tar | :
      - run:
          name: Build
          command: |
            DOCKER_TAG=<<parameters.docker_tag>>
            #docker build                           \
            #  --cache-from=app \
 
            docker build                           \
              -t innovanon/xmrig-cpu:$DOCKER_TAG   \
              --build-arg DOCKER_TAG="$DOCKER_TAG" \
              --pull .
      #- run:
      #    name: Save Docker image layer cache
      #    command: |
      #      mkdir -p /caches
      #      docker save -o /caches/app.tar app
      #- save_cache:
      #    key: v1-{{ .Branch }}-{{ epoch }}
      #    paths:
      #      - /caches/app.tar
      - run:
          name: Test
          command: |
            DOCKER_TAG=<<parameters.docker_tag>>
            [[ "$DOCKER_TAG" = native  ]] ||
            [[ "$DOCKER_TAG" = generic ]] ||
            exit 0

            CID="`docker run -d --rm innovanon/xmrig-cpu:$DOCKER_TAG`"
            echo "CID=$CID"

            docker ps -a | grep "${CID::12}"
            sleep 19
            #sleep 19
            #docker ps -a | grep "${CID::12}"
            #sleep 19
            #docker ps -a | grep "${CID::12}"
            #sleep 19
            #docker ps -a | grep "${CID::12}"
            #sleep 19
            docker ps -a | grep "${CID::12}"

            # TODO trigger dockerhub, don't build automatically
            echo TODO trigger dockerhub

            docker stop "$CID"

jobs:
  build-xmrig-cpu:
    machine: true
      #docker_layer_caching: true
    steps:
      - build
  build-xmrig-cpu-generic:
    machine: true
      #docker_layer_caching: true
    steps:
      - build:
          docker_tag: "generic"
      # TODO push to dockerhub
  build-xmrig-cpu-sandybridge:
    machine: true
      #docker_layer_caching: true
    steps:
      - build:
          docker_tag: "sandybridge"
      # TODO push to dockerhub
  build-xmrig-cpu-nehalem:
    machine: true
      #docker_layer_caching: true
    steps:
      - build:
          docker_tag: "nehalem"
      # TODO push to dockerhub
  build-xmrig-cpu-core2:
    machine: true
      #docker_layer_caching: true
    steps:
      - build:
          docker_tag: "core2"
      # TODO push to dockerhub

workflows:
  build-xmrig-cpu:
    jobs:
      - build-xmrig-cpu
      #- build-xmrig-cpu-generic
      #- build-xmrig-cpu-sandybridge
      #- build-xmrig-cpu-nehalem
      #- build-xmrig-cpu-core2

